#Wherever to delegate checking for the beam intersection to the client
#Final check is performed on the server to prevent malicious clients
#This probably should always stay as false
beam_client_check = false
#How often (in ticks) to scan for players intersecting the beacon
#Range: 1 ~ 5
beam_check_period = 5

#Category for End Crystal related things
["End Crystal options"]
	#How many End Crystals can be connected to the same Beacon at once?
	#Existing crystals won't disconnect if the value is decreased!
	#Range: 0 ~ 64
	end_crystals_per_beacon = 4
	#Max distance at which End Crystals are allowed to connect to the Beacons
	#Existing crystals won't disconnect if the value is decreased!
	#Range: 4 ~ 64
	end_crystal_max_distance = 16
