stages:
  - build-stage-1
  - build-stage-2
  - build-stage-3
  - push

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - changes:
      - minecraft/**/*

default:
  interruptible: false
  image:
    name: docker.io/library/docker:27.2.1
  services:
    - name: docker.io/library/docker:27.2.1-dind
      alias: docker
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: true
  MINECRAFT_VERSION: "1.21"
  FABRIC_LOADER_VERSION: 0.16.5
  FABRIC_LOADER_CHECKSUM: sha256:ccf2b6e4432805d5676e8f6634377a58e3642a6fdd3df0afa8cab8498c77ae85
  FABRIC_INSTALLER_VERSION: 1.0.1
  YARN_MAPPINGS_VERSION: 1.21+build.9
  OTEL_JAVAAGENT_VERSION: 1.33.5
  OTEL_JAVAAGENT_CHECKSUM: sha256:e77f7f3e2f2601a288bd8cb9deb7e2f9578034344e761587f51f03e097ae02ce

build_minecraft_builder:
  stage: build-stage-1
  tags:
    - saas-linux-small-amd64
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  script:
    - docker pull $CI_REGISTRY_IMAGE:builder-$ARCH || true
    - >
      docker build
      --pull
      --push
      --cache-from $CI_REGISTRY_IMAGE:builder-$ARCH
      --cache-to type=inline
      --target builder
      --platform "linux/$ARCH"
      --build-arg "MODRINTH_PAT=$MODRINTH_PAT"
      --build-arg "MINECRAFT_VERSION=$MINECRAFT_VERSION"
      --build-arg "FABRIC_LOADER_VERSION=$FABRIC_LOADER_VERSION"
      --build-arg "FABRIC_LOADER_CHECKSUM=$FABRIC_LOADER_CHECKSUM"
      --build-arg "FABRIC_INSTALLER_VERSION=$FABRIC_INSTALLER_VERSION"
      --build-arg "YARN_MAPPINGS_VERSION=$YARN_MAPPINGS_VERSION"
      --build-arg "OTEL_JAVAAGENT_VERSION=$OTEL_JAVAAGENT_VERSION"
      --build-arg "OTEL_JAVAAGENT_CHECKSUM=$OTEL_JAVAAGENT_CHECKSUM"
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $CI_REGISTRY_IMAGE:builder-$ARCH
      ./minecraft

build_minecraft_downloader:
  stage: build-stage-1
  tags:
    - saas-linux-small-amd64
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  script:
    - docker pull $CI_REGISTRY_IMAGE:downloader-$ARCH || true
    - >
      docker build
      --pull
      --push
      --cache-from $CI_REGISTRY_IMAGE:downloader-$ARCH
      --cache-to type=inline
      --target downloader
      --platform "linux/$ARCH"
      --build-arg "MODRINTH_PAT=$MODRINTH_PAT"
      --build-arg "MINECRAFT_VERSION=$MINECRAFT_VERSION"
      --build-arg "FABRIC_LOADER_VERSION=$FABRIC_LOADER_VERSION"
      --build-arg "FABRIC_LOADER_CHECKSUM=$FABRIC_LOADER_CHECKSUM"
      --build-arg "FABRIC_INSTALLER_VERSION=$FABRIC_INSTALLER_VERSION"
      --build-arg "YARN_MAPPINGS_VERSION=$YARN_MAPPINGS_VERSION"
      --build-arg "OTEL_JAVAAGENT_VERSION=$OTEL_JAVAAGENT_VERSION"
      --build-arg "OTEL_JAVAAGENT_CHECKSUM=$OTEL_JAVAAGENT_CHECKSUM"
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $CI_REGISTRY_IMAGE:downloader-$ARCH
      ./minecraft

build_minecraft:
  stage: build-stage-2
  tags:
    - saas-linux-small-amd64
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  script:
    - docker pull $CI_REGISTRY_IMAGE:builder-$ARCH || true
    - docker pull $CI_REGISTRY_IMAGE:downloader-$ARCH || true
    - docker pull $CI_REGISTRY_IMAGE:latest-$ARCH || true
    - >
      docker build
      --pull
      --push
      --cache-from $CI_REGISTRY_IMAGE:builder-$ARCH
      --cache-from $CI_REGISTRY_IMAGE:downloader-$ARCH
      --cache-from $CI_REGISTRY_IMAGE:latest-$ARCH
      --cache-to type=inline
      --platform "linux/$ARCH"
      --build-arg "MODRINTH_PAT=$MODRINTH_PAT"
      --build-arg "MINECRAFT_VERSION=$MINECRAFT_VERSION"
      --build-arg "FABRIC_LOADER_VERSION=$FABRIC_LOADER_VERSION"
      --build-arg "FABRIC_LOADER_CHECKSUM=$FABRIC_LOADER_CHECKSUM"
      --build-arg "FABRIC_INSTALLER_VERSION=$FABRIC_INSTALLER_VERSION"
      --build-arg "YARN_MAPPINGS_VERSION=$YARN_MAPPINGS_VERSION"
      --build-arg "OTEL_JAVAAGENT_VERSION=$OTEL_JAVAAGENT_VERSION"
      --build-arg "OTEL_JAVAAGENT_CHECKSUM=$OTEL_JAVAAGENT_CHECKSUM"
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-$ARCH
      ./minecraft

build_minecraft_multiarch:
  stage: build-stage-3
  script:
    - >
      docker manifest create
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-amd64
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-arm64
    - docker manifest push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

push_minecraft_latest:
  stage: push
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

push_minecraft_tagged:
  stage: push
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
