repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: 'minecraft/config/.*$'
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude_types:
          - rust
      - id: check-json
        exclude: 'minecraft/config/.*$'
      - id: check-yaml
        exclude: 'minecraft/config/.*$'
      - id: end-of-file-fixer
        exclude: 'minecraft/config/.*$'
      - id: fix-byte-order-marker
        exclude: 'minecraft/config/.*$'
      - id: mixed-line-ending
        exclude: 'minecraft/config/.*$'

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        exclude_types:
          - rust

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
