name: minecraft
services:
  minecraft:
    image: registry.gitlab.com/nausicaea/minecraft:latest
    build:
      context: minecraft
      args:
        MINECRAFT_VERSION: "1.21.1"
        FABRIC_LOADER_VERSION: 0.16.5
        FABRIC_LOADER_CHECKSUM: sha256:243ac92e0ddb12b031218d46d71f211d99d4d61a73fb2538bf73beee1ab37556
        FABRIC_INSTALLER_VERSION: 1.0.1
        YARN_MAPPINGS_VERSION: 1.21.1+build.3
        OTEL_JAVAAGENT_VERSION: 1.33.5
        OTEL_JAVAAGENT_CHECKSUM: sha256:e77f7f3e2f2601a288bd8cb9deb7e2f9578034344e761587f51f03e097ae02ce
    container_name: minecraft
    healthcheck:
      test: ['CMD', '/bin/healthcheck']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 2m
      start_interval: 5s
    environment:
      MINECRAFT_SERVER_ID: nausicaea
      JAVA_INITIAL_MEM: 256M
      JAVA_MAX_MEM: ${JAVA_MAX_MEM}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    volumes:
      - ./minecraft/server.properties:/var/lib/minecraft/server-config/server.properties:ro
      - ./minecraft/opentelemetry.properties:/var/lib/minecraft/server-config/opentelemetry.properties:ro
      - ./minecraft/log4j2.xml:/var/lib/minecraft/server-config/log4j2.xml:ro
      - backups:/var/lib/minecraft/backups
      - cache:/var/lib/minecraft/.fabric
      - crash_reports:/var/lib/minecraft/crash-reports
      - logs:/var/lib/minecraft/logs
      - mod_config:/var/lib/minecraft/config
      - player_config:/var/lib/minecraft/player-config
      - universe:/var/lib/minecraft/universe
    expose:
      - 30000/tcp
      - 30000/udp
      - 30001/udp
    mem_limit: ${MINECRAFT_MEM_LIMIT}

volumes:
  backups: {}
  cache: {}
  crash_reports: {}
  logs: {}
  mod_config: {}
  player_config: {}
  universe: {}
