name: minecraft
services:
  minecraft:
    image: nausicaea/dvergr:local
    build:
      context: minecraft
      args:
        MINECRAFT_VERSION: "1.21.4"
        FABRIC_LOADER_VERSION: 0.17.2
        FABRIC_LOADER_CHECKSUM: sha256:add80665872fe168a57dfae323ac6aee11e885d9cd97faee9ae05a6f1f65b010
        FABRIC_INSTALLER_VERSION: 1.1.0
        YARN_MAPPINGS_VERSION: 1.21.4+build.8
        OTEL_JAVAAGENT_VERSION: 2.19.0
        OTEL_JAVAAGENT_CHECKSUM: sha256:2bc973b5a5b61e7852df66be6388947f1b824b48d404ab5356fec464d0249869
        OTEL_MOD_VERSION: 1.0.3+1-21-4
        OTEL_MOD_CHECKSUM: sha256:bc42963ac09b56c715eaa1554b08e850517394893be482f07ba35531d4e31cad
        PARABURDOO_VERSION: 1.0.0+1-21-4
        PARABURDOO_CHECKSUM: sha256:3321bb77bac48223fe9a5b1b0e546bb78bae2c1a7d10b39bfd169fe3db8e61de
    container_name: minecraft
    stdin_open: true
    tty: true
    #entrypoint: ["/bin/sh", "-c", "while true; do sleep 1; done"]
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 2m
      start_interval: 5s
    environment:
      MINECRAFT_SERVER_ID: minecraft
      JAVA_INITIAL_MEM: 256M
      JAVA_MAX_MEM: 2G
    volumes:
      - persistent:/var/lib/minecraft/persistent
      - config:/etc/minecraft
      - cache:/var/cache/minecraft
      - logs:/var/log/minecraft
    expose:
      - 25565/tcp
      - 25565/udp
    ports:
      - 127.0.0.1:25565:25565/tcp
      - 127.0.0.1:25565:25565/udp
    mem_limit: 2G

volumes:
  # pvc/pv
  persistent: {}
  # emptyDir <- copy over from init container
  config: {}
  # emptyDir
  cache: {}
  # emptyDir
  logs: {}
