name: minecraft
services:
  minecraft:
    image: nausicaea/dvergr:local
    build:
      context: minecraft
      args:
        MINECRAFT_VERSION: "1.21.4"
        FABRIC_LOADER_VERSION: 0.16.14
        FABRIC_LOADER_CHECKSUM: sha256:c5074fbaba7834d43d9bbed0be159735e798bfe4eaf735c25c825e659fe2ab03
        FABRIC_INSTALLER_VERSION: 1.0.3
        YARN_MAPPINGS_VERSION: 1.21.4+build.8
        OTEL_JAVAAGENT_VERSION: 2.18.1
        OTEL_JAVAAGENT_CHECKSUM: sha256:f5fafdc5684139b04db461c420a46630acf598b44de951efd756e68a73778cfa
        JOLOKIA_JAVAAGENT_VERSION: 2.2.9
        JOLOKIA_JAVAAGENT_CHECKSUM: sha256:f5c4b31eeeb602888346ce7b545a885cb7caf932eff3b1b630e93cc720483429
        OTEL_MOD_VERSION: 1.0.3+1-21-4
        OTEL_MOD_CHECKSUM: sha256:bc42963ac09b56c715eaa1554b08e850517394893be482f07ba35531d4e31cad
    container_name: minecraft
    #entrypoint: ["/bin/sh", "-c", "while true; do sleep 1; done"]
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 2m
      start_interval: 5s
    environment:
      MINECRAFT_SERVER_ID: minecraft
      JAVA_INITIAL_MEM: 256M
      JAVA_MAX_MEM: 2G
      JOLOKIA_BIND_ADDRESS: "0.0.0.0:9422"
    volumes:
      - persistent:/var/lib/minecraft/persistent
      - config:/etc/minecraft
      - cache:/var/cache/minecraft
      - logs:/var/log/minecraft
    expose:
      - 30000/tcp
      - 30000/udp
      - 9422/tcp
    ports:
      - 127.0.0.1:25565:30000/tcp
      - 127.0.0.1:25565:30000/udp
    mem_limit: 2G

volumes:
  # pvc/pv
  persistent: {}
  # emptyDir <- copy over from init container
  config: {}
  # emptyDir
  cache: {}
  # emptyDir
  logs: {}
