name: minecraft
services:
  minecraft:
    image: nausicaea/minecraft:latest
    build:
      context: ./image
      args:
        MINECRAFT_VERSION: 1.20.1
        MINECRAFT_SERVER_ID: nausicaea
    container_name: minecraft
    environment:
      JAVA_MAX_MEM: 4G
    configs:
      - source: minecraft-logging
        target: /var/lib/minecraft/log4j2.xml
      - source: minecraft-server
        target: /var/lib/minecraft/server.properties
      - source: minecraft-operators
        target: /var/lib/minecraft/ops.json
      - source: minecraft-whitelist
        target: /var/lib/minecraft/whitelist.json
      - source: minecraft-banned-ips
        target: /var/lib/minecraft/banned-ips.json
      - source: minecraft-banned-players
        target: /var/lib/minecraft/banned-players.json
    volumes:
      - type: volume
        source: cache
        target: /var/lib/minecraft/.cache
      - type: volume
        source: universe
        target: /var/lib/minecraft/universe
      - type: volume
        source: mod-config
        target: /var/lib/minecraft/config
    ports:
      - 25565:25565/tcp
    restart: always
    cpus: 4
    mem_limit: "4G"

configs:
  minecraft-logging:
    file: ./config/log4j2.xml
  minecraft-server:
    file: ./config/server.properties
  minecraft-operators:
    file: ./config/ops.json
  minecraft-whitelist:
    file: ./config/whitelist.json
  minecraft-banned-ips:
    content: "[]"
  minecraft-banned-players:
    content: "[]"

volumes:
  cache: {}
  universe: {}
  mod-config: {}
