name: minecraft
services:
  minecraft_setup:
    image: &minecraft nausicaea/minecraft:latest
    build:
      context: minecraft
      args:
        MINECRAFT_VERSION: 1.20.1
    container_name: minecraft_setup
    user: root
    entrypoint: 
      - chown
      - "-R"
      - "100:101"
      - /var/lib/minecraft
    volumes:
      - backups:/var/lib/minecraft/backups
      - cache:/var/lib/minecraft/.cache
      - logs:/var/lib/minecraft/logs
      - crash_reports:/var/lib/minecraft/crash-reports
      - universe:/var/lib/minecraft/universe

  minecraft:
    image: *minecraft
    container_name: minecraft
    environment:
      MINECRAFT_SERVER_ID: nausicaea
      JAVA_INITIAL_MEM: 256M
      JAVA_MAX_MEM: ${JAVA_MAX_MEM}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel_collector:4317
    volumes:
      - ./mounts/log4j2.xml:/var/lib/minecraft/log4j2.xml:ro
      - ./mounts/opentelemetry.properties:/var/lib/minecraft/opentelemetry.properties:ro
      - ./mounts/server.properties:/var/lib/minecraft/server.properties
      - ./mounts/ops.json:/var/lib/minecraft/ops.json
      - ./mounts/whitelist.json:/var/lib/minecraft/whitelist.json
      - ./mounts/banned-ips.json:/var/lib/minecraft/banned-ips.json
      - ./mounts/banned-players.json:/var/lib/minecraft/banned-players.json
      - ./mounts/config:/var/lib/minecraft/config
      - ./mounts/mods:/var/lib/minecraft/mods
      - ./mounts/datapacks:/var/lib/minecraft/datapacks
      - backups:/var/lib/minecraft/backups
      - cache:/var/lib/minecraft/.cache
      - logs:/var/lib/minecraft/logs
      - crash_reports:/var/lib/minecraft/crash-reports
      - universe:/var/lib/minecraft/universe
    ports:
      - 25565:25565/tcp
      - 24454:24454/udp
    depends_on:
      - minecraft_setup
    mem_limit: ${MINECRAFT_MEM_LIMIT}

  otel_collector:
    image: docker.io/otel/opentelemetry-collector:latest
    container_name: otel_collector
    command: 
      - --config=/etc/otel-collector.yaml
    volumes:
      - ./otel/otel-collector.yaml:/etc/otel-collector.yaml:ro

  tempo_setup:
    image: &tempo docker.io/grafana/tempo:latest
    container_name: tempo_setup
    user: root
    entrypoint:
      - chown
      - "-R"
      - "10001:10001"
      - /var/tempo
    volumes:
      - tempo:/var/tempo

  tempo:
    image: *tempo
    container_name: tempo
    command: 
      - --config.file=/etc/tempo.yaml
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml:ro
      - tempo:/var/tempo
    depends_on:
      - tempo_setup

  loki_setup:
    image: &loki docker.io/grafana/loki:3.1.1
    container_name: loki_setup
    user: root
    entrypoint:
      - chown
      - "-R"
      - "10001:10001"
      - /var/loki
    volumes:
      - loki:/var/loki

  loki:
    image: *loki
    container_name: loki
    command: 
      - --config.file=/etc/loki.yaml
    volumes:
      - ./loki/loki.yaml:/etc/loki.yaml:ro
      - loki:/var/loki
    depends_on:
      - loki_setup

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    command: 
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus.yaml:ro
      - prometheus:/prometheus

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_BASIC_ENABLED: false
      GF_FEATURE_TOGGLES_ENABLE: accessControlOnCall,traceqlEditor
      GF_INSTALL_PLUGINS: https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

volumes:
  backups: {}
  cache: {}
  logs: {}
  crash_reports: {}
  universe: {}
  tempo: {}
  loki: {}
  prometheus: {}
  grafana: {}
