name: minecraft
services:
  minecraft:
    image: nausicaea/minecraft:local
    build:
      context: minecraft
      args:
        MINECRAFT_VERSION: "1.21.1"
        FABRIC_LOADER_VERSION: 0.16.14
        FABRIC_LOADER_CHECKSUM: sha256:44f3e6cfbefce7bc8761c3b45293d99edf2677ed947021a5ca6481907430c5aa
        FABRIC_INSTALLER_VERSION: 1.0.3
        YARN_MAPPINGS_VERSION: 1.21.1+build.3
        OTEL_JAVAAGENT_VERSION: 2.18.1
        OTEL_JAVAAGENT_CHECKSUM: sha256:f5fafdc5684139b04db461c420a46630acf598b44de951efd756e68a73778cfa
    container_name: minecraft
    healthcheck:
      test: ['CMD', '/bin/healthcheck']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 2m
      start_interval: 5s
    environment:
      MINECRAFT_SERVER_ID: nausicaea
      JAVA_INITIAL_MEM: 256M
      JAVA_MAX_MEM: ${JAVA_MAX_MEM}
    volumes:
      - ./minecraft/server.properties:/var/lib/minecraft/server-config/server.properties:ro
      - ./minecraft/opentelemetry.properties:/var/lib/minecraft/server-config/opentelemetry.properties:ro
      - ./minecraft/log4j2.xml:/var/lib/minecraft/server-config/log4j2.xml:ro
      - backups:/var/lib/minecraft/backups
      - cache:/var/lib/minecraft/.fabric
      - crash_reports:/var/lib/minecraft/crash-reports
      - logs:/var/lib/minecraft/logs
      - mod_config:/var/lib/minecraft/config
      - player_config:/var/lib/minecraft/player-config
      - universe:/var/lib/minecraft/universe
    expose:
      - 30000/tcp
      - 30000/udp
      - 30001/udp
    mem_limit: ${MINECRAFT_MEM_LIMIT}

volumes:
  backups: {}
  cache: {}
  crash_reports: {}
  logs: {}
  mod_config: {}
  player_config: {}
  universe: {}
