name: minecraft
services:
  minecraft:
    image: nausicaea/minecraft:latest
    build:
      context: ./image
      args:
        MINECRAFT_VERSION: 1.20.1
        MINECRAFT_SERVER_ID: nausicaea
    container_name: minecraft
    environment:
      JAVA_MAX_MEM: 4G
    volumes:
      - type: volume
        source: audioplayer_uploads
        target: /var/lib/minecraft/audioplayer_uploads
      - type: volume
        source: backups
        target: /var/lib/minecraft/backups
      - type: volume
        source: cache
        target: /var/lib/minecraft/.cache
      - type: volume
        source: mod_config
        target: /var/lib/minecraft/config
      - type: volume
        source: logs
        target: /var/lib/minecraft/logs
      - type: volume
        source: players
        target: /var/lib/minecraft/players
      - type: volume
        source: server_config
        target: /var/lib/minecraft/server
        read_only: true
      - type: volume
        source: universe
        target: /var/lib/minecraft/universe
    ports:
      - 25565:25565/tcp
      - 24454:24454/udp
    restart: always
    cpus: 4
    mem_limit: "4G"

volumes:
  audioplayer_uploads: {}
  backups: {}
  cache: {}
  logs: {}
  mod_config: {}
  players: {}
  server_config: {}
  universe: {}
