global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: tempo
    static_configs:
      - targets:
        - tempo:3200
  - job_name: loki
    static_configs:
      - targets:
        - loki:3100
  - job_name: otel_collector
    static_configs:
      - targets:
        - otel_collector:8888
