apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
  labels:
    app: otelcol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
    spec:
      containers:
        - name: main
          image: docker.io/otel/opentelemetry-collector:0.109.0
          command:
            - /otelcol
            - --config=/etc/otelcol/config.yaml
          volumeMounts:
            - name: otelcol-config
              mountPath: /etc/otelcol
          ports:
            - name: otlp
              containerPort: 4317
            - name: otelcol-metrics
              containerPort: 8888
      volumes:
        - name: otelcol-config
          configMap:
            name: opentelemetry-collector
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  labels:
    app: otelcol
spec:
  selector:
    app: otelcol
  ports:
    - name: otlp
      port: 4317
      targetPort: otlp
    - name: otelcol-metrics
      port: 8888
      targetPort: otelcol-metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
  labels:
    app: otelcol
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch: {}

    exporters:
      debug: {}
      otlp/traces:
        endpoint: http://tempo:4317
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: http://prometheus:9090/api/v1/write
        tls:
          insecure: true
      otlphttp/logs:
        endpoint: http://loki:3100/otlp

    service:
      telemetry:
        logs:
          level: INFO
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/traces]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/logs]
