---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  selector:
    app: minecraft
  type: LoadBalancer
  ports:
    - name: minecraft
      port: 30000
      protocol: TCP
      targetPort: minecraft
    - name: discovery
      port: 30000
      protocol: UDP
      targetPort: discovery
