[datapack]
sleep = "*"
vegan-recipes = "*"
"william-wythers-overhauled-overworld-(datapack)" = "*"
towering-tepuis = "*"
cliffs-and-coves = "*"
navigable-rivers = "*"
new-in-town = "*"
new-in-town-dimensions = "*"
mystcraft-data-pack = "*"
saturated = "*"

[fabric]
# Not compatible with > 1.21.1
#smsn = "*"
#mixintrace = "*"
#fabric-tps = "*"
#mod-viewer = "*"
#server-ui-fix = "*"
#polydex-bridge = "*"
#universal-perms = "*"

polydecorations = "*"
dynamic-lights = "*"
leaves-be-gone = "*"
lmd = "*"
midnightlib = "*"
ferrite-core = "*"
lithium = "*"
noisium = "*"
c2me-fabric = "*"
krypton = "*"
advanced-backups = "*"
stackdeobf = "*"
modernfix = "*"
sessility = "*"
coord-finder = "*"
goml-reserved = "*"
luckperms = "*"
tpa = "*"
polydex = "*"
vanilla-refresh = "*"
nullscape = "*"
polyfactory = "*"
arcana-novum = "*"
passivemobs = "*"
tectonic = "*"
melius-worldmanager = "*"
