minecraft_version = "1.21.4"

[datapack]
# Worldgen
"william-wythers-overhauled-overworld-(datapack)" = "*"
towering-tepuis = "*"
cliffs-and-coves = "*"
navigable-rivers = "*"
new-in-town-dimensions = "*"
mystcraft-data-pack = "*"
saturated = "*"

# # Other
sleep = "*"
vegan-recipes = "*"
new-in-town = "*"

[fabric]
# Worldgen
tectonic = "*"
mes-moogs-end-structures = "*"

# Polymerized
polydex = "*"
polydecorations = "*"
# trinkets-polymer = "*" # Causes loads of Exceptions "leaked resource" when starting the server
baby-fat-polymer = "*"
polyfactory = "*"
arcana-novum = "*"
server-storage = "*"  # https://modrinth.com/mod/server-storage

# Admin
advanced-backups = "*"
luckperms = "*"
stackdeobf = "*"
sessility = "*"
# spark = "*"
# otel-instrumentation-extension = "*"  # https://github.com/litetex-oss/mcm-otel-instrumentation-extension
# fabricexporter = "*"  # https://modrinth.com/mod/fabricexporter
ender-nexus = "*"  # https://modrinth.com/mod/ender-nexus
# fabric-trade = "*"  # https://modrinth.com/mod/fabric-trade

# Optimization
ferrite-core = "*"
lithium = "*"
noisium = "*"
c2me-fabric = "*"
krypton = "*"
modernfix = "*"

# Other
dynamic-lights = "*"
leaves-be-gone = "*"
lmd = "*"
midnightlib = "*"
goml-reserved = "*"
vanilla-refresh = "*"
# rei = "*"  # REI specifies being incompatible with dedicated servers, but in-game messages contradict that.
