[datapack]
# Worldgen (Overworld)
"william-wythers-overhauled-overworld-(datapack)" = "*"
towering-tepuis = "*"
cliffs-and-coves = "*"
navigable-rivers = "*"

# Worldgen (other)
new-in-town-dimensions = "*"
mystcraft-data-pack = "*"
saturated = "*"

# # Other
sleep = "*"
vegan-recipes = "*"
new-in-town = "*"

[fabric]
# Worldgen (Overworld)
tectonic = "*"

# Worldgen (other)
nullscape = "*"

# Polymerized
polydex = "*"
polydecorations = "*"
# trinkets-polymer = "*" # Causes loads of Exceptions "leaked resource" when starting the server
baby-fat-polymer = "*"
polyfactory = "*"
arcana-novum = "*"
# server-storage = "*"

# Admin
advanced-backups = "*"
luckperms = "*"
#melius-worldmanager = "*" # Cannot use Nether portals in overworld maps created by this mod
stackdeobf = "*"
coord-finder = "*"
# spark = "*"
# otel-instrumentation-extension = "*"  # https://github.com/litetex-oss/mcm-otel-instrumentation-extension
# fabricexporter = "*"  # https://modrinth.com/mod/fabricexporter

# Optimization
ferrite-core = "*"
lithium = "*"
noisium = "*"
c2me-fabric = "*"
krypton = "*"
modernfix = "*"

# Other
dynamic-lights = "*"
leaves-be-gone = "*"
lmd = "*"
midnightlib = "*"
sessility = "*"
goml-reserved = "*"
tpa = "*"
vanilla-refresh = "*"
passivemobs = "*"
fleeing-animals = "*"
