[datapack]
sleep = "*"
vegan-recipes = "*"
"william-wythers-overhauled-overworld-(datapack)" = "*"
towering-tepuis = "*"
cliffs-and-coves = "*"
navigable-rivers = "*"
new-in-town = "*"
new-in-town-dimensions = "*"

[fabric]
polydecorations = "*"
universal-perms = "*"
dynamic-lights = "*"
smsn = "*"
leaves-be-gone = "*"
lmd = "*"
midnightlib = "*"
ferrite-core = "*"
lithium = "*"
noisium = "*"
c2me-fabric = "*"
krypton = "*"
advanced-backups = "*"
mixintrace = "*"
stackdeobf = "*"
modernfix = "*"
sessility = "*"
fabric-tps = "*"
coord-finder = "*"
mod-viewer = "*"
goml-reserved = "*"
luckperms = "*"
tpa = "*"
server-ui-fix = "*"
polydex = "*"
polydex-bridge = "*"
vanilla-refresh = "*"
nullscape = "*"
polyfactory = "*"
arcana-novum = "*"
passivemobs = "*"
tectonic = "v2.4.1a"
