name: Minecraft Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: >
        docker build minecraft
        --build-arg "MODRINTH_PAT=$MODRINTH_PAT"
        --build-arg "MINECRAFT_VERSION=1.21"
        --build-arg "FABRIC_LOADER_VERSION=0.16.5"
        --build-arg "FABRIC_LOADER_CHECKSUM=sha256:ccf2b6e4432805d5676e8f6634377a58e3642a6fdd3df0afa8cab8498c77ae85"
        --build-arg "FABRIC_INSTALLER_VERSION=1.0.1"
        --build-arg "YARN_MAPPINGS_VERSION=1.21+build.9"
        --build-arg "OTEL_JAVAAGENT_VERSION=1.33.5"
        --build-arg "OTEL_JAVAAGENT_CHECKSUM=sha256:e77f7f3e2f2601a288bd8cb9deb7e2f9578034344e761587f51f03e097ae02ce"
        --file Dockerfile 
        --tag nausicaea/minecraft:$(date +%s)
